name: Deploy static content to Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Build your static site here (adjust as needed)
      - name: Build site
        run: echo "npm run build"

      # Upload build artifacts
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: site
          path: ./dist

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist
